# Creare un makefile con una regola help di default che mostri una nota informativa, 
# una regola backup che crei un backup di una cartella appendendo “.bak” al nome 
# e una restore che ripristini il contenuto originale. Per definire la cartella 
# sorgente passarne il nome come variabile, ad esempio:
# make -f mf-backup FOLDER=... 

hello:
	@echo "compilando..."
	@g++ Cfile.cpp
	@./a.out